export const images = {
  alchemist: [
    require("../images/alchemist/slezica_cute_alchemist.png"),
    require("../images/alchemist/slezica_cute_baby_rob14cccc419.png"),
    require("../images/alchemist/slezica_cute_clock_robot_7f209e3.png"),
    require("../images/alchemist/slezica_small_cute_spider_3466.png"),
    require("../images/alchemist/slezica_tiny_cute_happy_robot.png"),
  ],
  armorCat: [
    require("../images/armorCat/Originalv2.png"),
    require("../images/armorCat/Original.png"),
    require("../images/armorCat/v2UVS1.png"),
    require("../images/armorCat/v2UVS2.png"),
    require("../images/armorCat/v2UVS3.png"),
    require("../images/armorCat/v2UVS4.png"),
  ],
  body: [
    require("../images/body/Isaac_cinematic--a579aac3c36f.png"),
    require("../images/body/Isaac_cinematic--cfcef5b8bed7.png"),
    require("../images/body/Isaac_cinematic-9775116c8cb.png"),
    require("../images/body/Isaac_ultra-wide-3fc46c6f9691.png"),
    require("../images/body/Isaac_ultra-wide-89beb.png"),
  ],
  cuteGirl: [
    require("../images/cuteGirl/XSlayer300_Personification_fac76.png"),
    require("../images/cuteGirl/XSlayer300_Personification_of_4ef8.png"),
    require("../images/cuteGirl/XSlayer300_Personification_of_44eeab45f.png"),
    require("../images/cuteGirl/XSlayer300_Personification_of_848.png"),
  ],
  epicSpace: [
    require("../images/epic-space/That_Weird_Ghost_hyper_1c.jpg"),
    require("../images/epic-space/That_Weird_Ghost_hyper_2c8.jpg"),
    require("../images/epic-space/That_Weird_Ghost_hyper_9d1d.jpg"),
    require("../images/epic-space/That_Weird_Ghost_hyper_9d605.jpg"),
    require("../images/epic-space/That_Weird_Ghost_hyper_a598c.jpg"),
    require("../images/epic-space/That_Weird_Ghost_hyper_d110.jpg"),
  ],
  food: [
    require("../images/food/1.png"),
    require("../images/food/2.png"),
    require("../images/food/3.png"),
    require("../images/food/4.png"),
    require("../images/food/5.png"),
    require("../images/food/6.png"),
    require("../images/food/7.png"),
    require("../images/food/8.png"),
    require("../images/food/9.png"),
  ],

  investigator: [
    require("../images/investigator/That_Weird_Ghost_.jpg"),
    require("../images/investigator/That_Weird_Ghost_8c6.jpg"),
    require("../images/investigator/That_Weird_Ghost_045ae3c.jpg"),
    require("../images/investigator/That_Weird_Ghost_95.jpg"),
    require("../images/investigator/That_Weird_Ghost_163.jpg"),
    require("../images/investigator/That_Weird_Ghost_a87.jpg"),
    require("../images/investigator/That_Weird_Ghost_defebc7f.jpg"),
    require("../images/investigator/That_Weird_Ghost-89d5142c6f5a.jpg"),
    require("../images/investigator/That_Weird_Ghost93.jpg"),
  ],
  lionGod: [
    require("../images/lionGod/AICONNOR_The_ancient_.jpg"),
    require("../images/lionGod/AICONNOR_The_ancient_8d.jpg"),
    require("../images/lionGod/AICONNOR_The_ancient_80c25.jpg"),
    require("../images/lionGod/AICONNOR_The_ancient_black_225.jpg"),
    require("../images/lionGod/AICONNOR_The_ancient_black_b.jpg"),
    require("../images/lionGod/AICONNOR_The_ancient_black.jpg"),
    require("../images/lionGod/AICONNOR_The_ancient_black4a6f.jpg"),
  ],
  musical: [require("../images/musical/killamillar_musical_man_6beb.jpg")],
  popoutArt: [require("../images/popoutArt/Keitsu_artists_im.png")],
  sarent: [require("../images/sargent/Sharkysaur_fox_947d68f762a.jpg")],
  spaceFederation: [
    require("../images/spaceFederation/Heliosphere_5-30a5f9904f2d.jpg"),
  ],
  viking: [require("../images/viking/Penta_ultra-s9d91a1.png")],
  war: [require("../images/war/grid_0-4.webp")],
  winchester: [
    require("../images/winchester/TheWinchester1977-80b0-4524-9447-40c2e056d281.png"),
  ],
  wonamTatoo: [
    require("../images/womanTattos/Ssenmad_tattoo_79-42d9-b02f-0faaba3ba648.png"),
    require("../images/womanTattos/Ssenmad_tattoo96-2891-4020-b4b3-fb814ea80372.png"),
    require("../images/womanTattos/Ssenmad_tattoo4033-a7e3-b42fa308657f.png"),
    require("../images/womanTattos/Ssenmad_tattoob5c6-cf6bac59b6b3.png"),
    require("../images/womanTattos/Ssenmad_tattoode3-411c-9e02-3a3c63516a60.png"),
  ],
};
